# Generated by Django 3.2.18 on 2023-10-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=122)),
                ('password', models.CharField(max_length=122)),
                ('course', models.CharField(max_length=122)),
                ('amount', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(default='', max_length=12)),
            ],
        ),
    ]
