# Generated by Django 3.2.18 on 2023-10-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='amount',
            field=models.CharField(max_length=50),
        ),
    ]
